# Generated by Django 5.0.6 on 2024-06-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id_hotel', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CantidadTipoHabitacion',
            fields=[
                ('id_cant_tipo_habitacion', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_tipo_habitacion', models.IntegerField()),
                ('cantidad_habitacion', models.IntegerField()),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hoteles')),
            ],
            options={
                'db_table': 'app1_cantidad_tipo_habitacion',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_sercicio', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('servicio', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hoteles')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('tipo', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('camas', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hoteles')),
            ],
            options={
                'db_table': 'app1_tipo_habitaciones',
            },
        ),
    ]
