# Generated by Django 5.0.6 on 2024-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id_habitacion', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
