# Generated by Django 5.0.6 on 2024-07-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelHabitacion',
            fields=[
                ('id_hot_hav', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.PROTECT, to='app1.habitaciones')),
                ('id_hotel', models.ForeignKey(db_column='id_hotel', on_delete=django.db.models.deletion.PROTECT, to='app1.hoteles')),
            ],
        ),
    ]
