# Generated by Django 5.0.6 on 2024-07-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_hotelhabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=10)),
                ('f_inicio', models.DateField()),
                ('f_termino', models.DateField()),
                ('cantidad', models.IntegerField(max_length=10)),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.PROTECT, to='app1.habitaciones')),
                ('id_hotel', models.ForeignKey(db_column='id_hotel', on_delete=django.db.models.deletion.PROTECT, to='app1.hoteles')),
            ],
        ),
    ]
