# Generated by Django 5.0.6 on 2024-07-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_habitaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosExtras',
            fields=[
                ('id_serv_extras', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
