# Generated by Django 5.0.6 on 2024-07-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_reservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ReservasServiciosExtras',
            fields=[
                ('id_res_serv_extras', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.PROTECT, to='app1.reservas')),
                ('id_serivicio_extra', models.ForeignKey(db_column='id_servicio_extra', on_delete=django.db.models.deletion.PROTECT, to='app1.serviciosextras')),
            ],
        ),
    ]
