# Generated by Django 5.0.6 on 2024-07-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_reservas_cantidad_alter_reservas_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
